### ISSUE TITLE
I have already install the orbslam3,are there exsiting problems to excute this project?

### ISSUE THREAD

**Issue by cwahaha51** [CIFASIS/gnss-stereo-inertial-fusion#1]

**Comment by jcremona** [comment]
Hi! It should not be a problem, unless there is a version conflict with the dependencies of your installation of ORB-SLAM3. I could implement Docker support in the next few days. It will be based on the Docker support of https://github.com/CIFASIS/ORB_SLAM3/.

**Comment by jcremona** [comment]
A Dockerfile has been added to facilitate deployment and execution via Docker containers. Don't hesitate to ask if you need any guidance with using it
